version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - web
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5

  online-payment:
    depends_on:
      - postgres
    container_name: online-payment-v2
    build: .
    volumes:
      - ./:/usr/src/app
      - /etc/letsencrypt/live/ictinnovations.africa/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ictinnovations.africa/privkey.pem:/certs/privkey.pem:ro
    ports:
      - '8000:8000'
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --ssl-keyfile /certs/privkey.pem --ssl-certfile /certs/fullchain.pem
    networks:
      - web
    restart: on-failure
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - /etc/letsencrypt/live/ictinnovations.africa/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ictinnovations.africa/privkey.pem:/certs/privkey.pem:ro
    env_file:
      - .env
    networks:
      - web

networks:
  web:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
