name: online-payment-api CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.NEW_SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.NEW_SERVER }}
          USERNAME: ${{ secrets.NEW_USERNAME }}
        run: |
          # Start the SSH agent
          eval $(ssh-agent -s)

          # Add the private key to the SSH agent
          echo "$NEW_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          # Connect to the server and execute commands
          ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
            cd ~/online_payment_api_fastApi
            git pull origin main  # Pull the latest changes from GitHub
            docker compose down   # Stop and remove the running containers
            docker compose up -d --build  # Rebuild and start containers in the background
          EOF
